language: rust

rust: nightly

os:
  - linux
  - osx

# addons:
#   apt:
#     sources:
#       - kalakris-cmake
#     packages:
#       - cmake
#       - libcurl4-openssl-dev
#       - libelf-dev
#       - libdw-dev

script:
  - cargo build --verbose
  - RUST_BACKTRACE=full cargo test --verbose
