language: rust

rust: nightly

os:
  - linux
# coming soon:
# - osx

env:
  global:
    - RUST_BACKTRACE=full

script:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      # test output for a different libc is expected to be different
      mv tests/full_cases/libc-0.2.28-0.2.31.osx tests/full_cases/libc-0.2.28-0.2.31
    fi

    cargo build
    cargo test --verbose

    # install
    mkdir -p ~/rust/cargo/bin
    cp target/debug/cargo-semver ~/rust/cargo/bin
    cp target/debug/rust-semverver ~/rust/cargo/bin

    # become semververver
    eval "current_version=$(grep -e '^version = .*$' Cargo.toml | cut -d ' ' -f 3)"
    PATH=~/rust/cargo/bin:$PATH cargo semver | tee semver_out
    head -n 1 semver_out | grep "\-> $current_version"
    (head -n 1 semver_out | grep "\-> $current_version") || (echo "versioning mismatch" && return 1)
