[package]
name = "semverver"
description = "Automatic verification of SemVer adhrence in rust library crates"
repository = "https://github.com/rust-lang-nursery/rust-semverver"

readme = "README.md"
keywords = ["semver", "plugin"]
categories = ["development-tools", "development-tools::cargo-plugins"]

version = "0.1.11"

authors = ["Inokentiy Babushkin <twk@twki.de>"]
license-file = "LICENSE"

[badges]
travis-ci = { repository = "rust-lang-nursery/rust-semverver" }
appveyor = { repository = "rust-lang-nursery/rust-semverver" }

[[bin]]
name = "cargo-semver"
path = "src/bin/cargo_semver.rs"

[[bin]]
name = "rust-semverver"
path = "src/bin/rust_semverver.rs"

[dependencies]
cargo = "^0.27"
crates-io = "^0.16"
env_logger = "^0.5"
log = "^0.4"
semver = "^0.9"

[dev-dependencies]
quickcheck = "0.6"
